services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  user_service:
    build: ./user_service
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@postgres:5432/user_service_db
    ports:
      - "8001:8001"
    volumes:
      - ./user_service:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]

  embedding_service:
    build: ./embedding_service
    restart: always
    ports:
      - "8003:8003"
    volumes:
      - ./embedding_service:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8003"]

  job_service:
    build: ./job_service
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@postgres:5432/job_service_db
    ports:
      - "8004:8004"
    volumes:
      - ./job_service:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8004"]

volumes:
  pgdata:
