services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_service_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  user_service:
    build: ./user_service
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@postgres:5432/user_service_db
    ports:
      - "8001:8001"
    volumes:
      - ./user_service:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]

volumes:
  pgdata:
